project:
  type: website

website:
  title: "CIENTIFI KT"
  favicon: "images/Diseño sin título(10).jpg"
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    

editor: visual


